Enhancements to documentation
5G-MAG/Getting-Started pull request #93
Opened 2024-10-10 11:56 UTC by jordijoangimenez

General enhancements to documentation. Minor issues may still be outstanding but can be fixed in a second round of updates.
Slide decks will be propagated once agreed internally.

2024-10-11 09:00 UTC, dsilhavy requested changes

2024-10-11 09:00 UTC, dsilhavy commented on pages/3gpp-ran-and-core-platforms/repositories/repositories.md
> +* [srsRAN Project](www.srsran.com/), in its two variants:
This link seems to be broken because of missing `https://`

2024-10-11 09:00 UTC, dsilhavy commented on pages/3gpp-ran-and-core-platforms/repositories/repositories.md
> +* [Open5GS Project](www.open5gs.org), used primarily as the 5GC to build 5G-MAG Reference Tools demonstrators and PoCs and as the basis for the development of 5GC related components for MBS
This link seems to be broken because of missing `https://`

2024-10-11 09:00 UTC, dsilhavy commented on pages/5g-core-network-components/tutorials/tutorials.md
> +This guide describes how to setup and configure the 5G-MAG Reference Tools - 5G Downlink Media Streaming components to create an end to end setup using Application Function, Application Server, 5GMSd
5GMS is not included in the linked tutorial

2024-10-11 09:00 UTC, dsilhavy commented on pages/5g-media-streaming/repositories/repositories.md
I suggest to add a short note to the releases of the 5GMS Aware Application and the 5GMS Media Session Handler to indicate that the apks are also available in the Github releases:

* Releases (prebuilt APK available)

2024-10-11 09:00 UTC, dsilhavy commented on pages/5g-media-streaming/tutorials/tutorials.md
> +
Choose a different title, this is the same as the one above

2024-10-11 09:00 UTC, dsilhavy commented on pages/lte-based-5g-broadcast/features.md
Would be great to have a similar table for the QRD/CRD transmitter

2024-10-11 09:00 UTC, dsilhavy commented on pages/multimedia-content-delivery/index.md
On the specifications page I suggest to link to the ROUTE abd FLUTE specs:

*FLUTE: https://datatracker.ietf.org/doc/html/rfc6726
* ROUTE: https://www.atsc.org/wp-content/uploads/2024/04/A331-2024-04-Signaling-Delivery-Sync-FEC.pdf Annex A (Not sure if this is the right spec)

2024-10-11 19:08 UTC, jordijoangimenez commented on pages/lte-based-5g-broadcast/features.md
I've included a line with comments given the features of the tx are pre-release 14. I think we can add in the future some comments on the actual pre-Rel14 features but that needs a bit of digging into the code and into the specs.

2024-10-11 19:13 UTC, jordijoangimenez commented on pages/multimedia-content-delivery/index.md
We have this here: https://5g-mag.github.io/Standards/pages/multimedia-content-delivery/ietf-specifications.html
A bit hidden. I'll think how to go about it.

2024-10-11 19:13 UTC, jordijoangimenez commented
All resolved, thank you very much for the review!!

2024-10-12 06:27 UTC, dsilhavy approved these changes

2024-10-12 06:27 UTC, merged